# Generated by Django 2.1.5 on 2019-04-11 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('clas', models.PositiveIntegerField()),
                ('school', models.CharField(max_length=50)),
            ],
        ),
    ]
